#! /bin/sh

run=ryu-manager 
app=RestRequestAPI.py

if [  -n "$@" ]; then
    ${run} $app   
else
    if [ 'clean' = "$1" ]; then
        echo $1
        rm *.pyc
    elif [ 'run' = "$1" ]; then
       ${run} ${app}
    else
        echo "unkown parmameter\n"
    fi
fi



